# Workflow API version
apiVersion: io.orquestra.workflow/1.0.0

# Prefix for workflow ID
name: tutorial-2-workflow

# List components needed by workflow.
imports:
- name: sklearn-component
  type: git
  parameters:
    repository: "git@github.com:zapatacomputing/tutorial-orquestra-sklearn.git"
    branch: "master"

steps:

# This step runs the step that trains the model from the z-scikit-learn component
- name: perceptron-training
  config:
    runtime:
      type: python3
      imports: [sklearn-component]
      parameters:
        file: sklearn-component/steps/tutorial_2_step.py
        function: generate_train_step
  inputs:
    - dataset_name: "simple_dataset"
      type: string
    - model_name: "perceptron"
      type: string
  outputs:
  - name: result
    type: output

types:
 - output